### PR TITLE
Update basepom to java11

### PR DESCRIPTION
**Pull request by kmclarnon**
@stevegutz @Xcelled @jhaber

### CODE REVIEW

**Comment by kmclarnon** [comment]
Testing this with mothership internally

**Comment by stevegutz** [comment]
Nice, thank you! Does the internal test include `parent-pom` stuff? Cuz that will be affected too.

I was also thinking that it could make sense to cut a release before bumping all this stuff. Any thoughts on that?

**Comment by kmclarnon** [comment]
Yea, I ran a mothership mission using a branch of parent-pom that was based off of this basepom branch and things looked good.  I think cutting a release before merging this is a great idea, I can get that done.

**Comment by kmclarnon** [comment]
Superseded by https://github.com/HubSpot/basepom/pull/98

**Pull request closed without merging**
