### PR TITLE
Bump up dropwizard version

### PR DESCRIPTION
**Pull request by ikatkov**
Bump up dropwizard version to resolve https://github.com/dropwizard/dropwizard/issues/1761

### CODE REVIEW

**Comment by ikatkov** [comment]
If OK, please merge and release. I need to have dropwizard-guice patched and release 1.0.0.4

**Comment by jhaber** [comment]
Unfortunately I think we'll also need to bump HK2, Jersey, Jetty, and potentially other libraries as well. This is definitely on our to-do list though. Out of curiosity, if we went straight to dropwizard 1.0.6 would that work for you?

**Comment by ikatkov** [comment]
I tested 1.0.2 bump - no need to upgrade other libs.
With 1.0.5 there are three more changes. Did not check 1.0.6

**Comment by jhaber** [comment]
Interesting, that would be great if it's the case. I'll test this out soon and merge if there are no issues

**Comment by jhaber** [comment]
It seems like you're right! I'll merge and cut a new release and then upgrade dropwizard-guice and dropwizard-guicier to use the new basepom

**Comment by jhaber** [comment]
15.8 should show up in Maven Central soon

**Comment by ikatkov** [comment]
still not there

**Comment by jhaber** [comment]
I see the new version (15.8) [here](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.hubspot%22%20AND%20a%3A%22basepom%22). I'll work on moving dropwizard-guice and dropwizard-guicier to use this new version today

**Comment by jhaber** [comment]
I just released dropwizard-guice and dropwizard-guicier version 1.0.2.0, they should show up in Maven Central shortly

**Pull request merged**
