### PR TITLE
Upgrade surefire

### PR DESCRIPTION
**Pull request by jhaber**
I renamed all of our failing `*Tests` classes to `*IT` so we should be able to upgrade without breaking stuff

### CODE REVIEW

**Comment by jhaber** [comment]
@stevegutz

**Comment by stevegutz** [comment]
LGTM if all the renaming PRs are merged.

**Comment by stevegutz** [comment]
Actually, we can just delete the property

**Comment by jhaber** [comment]
basepom isn't on latest surefire, I'm not sure if there's an urgent need to go latest but that's what I was testing against so I figured why not

**Comment by stevegutz** [comment]
Cool, sounds good. I guess my one concern is that we might miss the next surefire upgrade because we override it here.

**Comment by jhaber** [comment]
I added a comment that this is to pick up a newer version and not to lock to 2.21.0

**Pull request merged**
