### PR TITLE
3.20.0-GA -> 3.22.0.GA

### PR DESCRIPTION
**Pull request by szabowexler**
What it says on the tin.

@jhaber @stevegutz

### CODE REVIEW

**Comment by jhaber** [comment]
Seems fine to me, though I wonder if we should just go straight to 3.22.0.GA

**Comment by szabowexler** [comment]
Sure

**Comment by jhaber** [comment]
🚢

**Comment by stevegutz** [comment]
LGTM, I checked binary compat for this and it seems fine given our use case

**Pull request merged**
