### PR TITLE
Upgrade to basepom 18

### PR DESCRIPTION
**Pull request by jhaber**
This at least gets rid of the errors about `org.eclipse.m2e:lifecycle-mapping:jar:1.0.0`

@stevegutz

### CODE REVIEW

**Comment by jhaber** [comment]
I tested with a few of our open-source projects (including Singularity) and they built fine

**Comment by stevegutz** [comment]
Can you check a few things on `parent-pom` too?

**Comment by jhaber** [comment]
Sure, looks good as well

**Comment by stevegutz** [comment]
LGTM.

We could also do a release of the current version before doing this, though I don't know that that matters.

**Comment by jhaber** [comment]
That sounds good, I'll release 15.17 and then 18.0

**Pull request merged**
